### ISSUE TITLE
Constructing the list for parameters

### ISSUE THREAD

**Issue by Becheler** [stdupas/EnvironmentalDemogeneticsABC#3]
Je pensais à construire la liste de cette manière, ça conviendrait ? Comme faut pas pusher Mémé dans les orties, j'ai préféré ouvrir une issue.

```
# prior function to call to get its parameters (with uniform it's not really interesting, but with others...)
uniform <- function(n, min, max){runif(n=n, min=min,max=max)}

simulations <-list(Niche=list(), Dispersion=list(), Mutation=list())
for(envrt_variable in names(rasterStack)) # envrt_variable <- "BIO1"
{
  # add a box "BIO1" in simulation$Niche
  simulations[["Niche"]][[envrt_variable]] <- list()
  model <- readline(paste0("Which niche model do you want for",envrt_variable,"? ")) # TODO : envelinear

  for(niche_parameter in names(formals(model))) # niche_parameter="X"
  {
    # add a box "X in simulations$Niche$BIO1
    simulations[["Niche"]][[envrt_variable]][[niche_parameter]] <- list()
    prior <- readline(paste0("Which prior model do you want for",niche_parameter,"? ")) # TODO : uniform

    for(prior_parameter in names(formals(prior))) # prior_parameter = "n"
    {
      # add a box "n" in simulation$Niche$BIO1$X
      simulations[["Niche"]][[envrt_variable]][[niche_parameter]][[prior_parameter]] <- numeric()

    }
  }
}

```

**Comment by Becheler** [comment]
Je reviens sur l'autre solution proposée pour obtenir les arguments :

```
react_norm_param <- function(shapes)
{
  params = NULL
  for (shape in shapes)
  {
  params = append(params, switch(shape,
           constant = paste(names(rasterStack),".Y",sep=""),
           enveloppe = combine.names(names(rasterStack),c("Xmin","Xmax","Yopt")),
           envelin = combine.names(names(rasterStack),c("Yxmin","Yxmax","Xmin","Xmax")),
           envloglin = combine.names(names(rasterStack),c("Yxmin","Yxmax","Xmin","Xmax")),
           linear = combine.names(names(rasterStack),c("X0","slope")),
           linearPositive = combine.names(names(rasterStack),c("X0","slope")),
           conquadratic = combine.names(names(rasterStack),c("Xmin","Xmax","Yopt")),
           conquadraticsq = combine.names(names(rasterStack),c("Xmin","Xmax","Yopt")),
           conquadraticskewed = combine.names(names(rasterStack),c("Xmin","Xmax","Xopt","Yopt")),
           conquadraticskewedsq = combine.names(names(rasterStack),c("Xmin","Xmax","Xopt","Yopt"))
                                )
           )
  }
params
}
```

Cela me paraît moins souple, car une simple modification (pour les noms d'arguments) ou ajout d'une fonction de niche entraînerait de devoir modifier également le code relatif à la création de la liste. C'est tout l'intérêt (il me semble) du `names(formals(function))` : il suffit de donner à la fonction de niche un nom suffisamment explicite pour que l'utilisateur la rentre, et que la liste soit immédiatement étendue en fonction des arguments ainsi renvoyés. Et donc pas besoin d'écrire une fonction de correspondance méthode<=>arguments susceptible de devoir être sans cesse réactualisée (il suffira de modifier directement la fonction de niche). Un autre avantage est que c'est extensible aux fonctions de dispersion et de migration : une seule fonction pour tout ! Tu en penses quoi ? :)

**Comment by Becheler** [comment]
"Seul" souci, c'est qu'il faudra reformater les fonctions de niche, dispersion et migration, pour qu'elles prennent toutes leurs arguments dans le format suivant {valeur, paramètre1, param2...} avec "valeur" correspondant à l'objet le plus simple (pas une matrice de valeurs). Par exemple dans conquadraticskewed, définir une fonction plus simple qui fait le coeur du calcul (x -> f(x)), avec comme simple arguments {x, Yopt, Xopt, Xmin, Xmax } quitte à l'englober avec un apply, mapply... pour l'utiliser sur des objets plus complexes. Mais là, on devrait parvenir à trouver une seule fonction de généralisation applicable à toutes les fonctions de niche (ou de dispersion), ce qui rendrait le code plus propre (enfin... je crois ? ¬¬ )

**Comment by Becheler** [comment]
Bon, j'ai pushé une nouvelle branche "NicheFunctions", sur laquelle je transforme les fonction de niche et de migration (pour les mutations, ça a l'air plus sioux). J'ai ajouté des nouveaux fichiers relatifs à chaque catégorie Niche/Dispersion/Mutation. Ca éclaircit le fichier de source et facilite les manipulations, rajouts de modèle etc. Faudra que je rentre ces détails dans le README, qui sert également à ça je crois bien... :)
On peut travailler sur branches séparée pour l'instant, ça vaut peut être mieux pour éviter de se court circuiter d'ici Lundi.

**Comment by stdupas** [comment]
ok super. Comment on pull une branche (désolé j'ai pas ton pense bête), j'ai essaye git pull origin NicheFunctions, ça a pas marché

**Comment by stdupas** [comment]
C'est bien ta solution. Il faudra donc éliminer ce switch au sein de la fonction reaction_norm, et demander directement la norme de réaction qui convient à partir de la liste entrée. De même pour toutes les fonctions de mutation, faire une fonction par modèle de mutation. Et plus de switch. Pareil pour la dispersion. C'est ça?

**Comment by Becheler** [comment]
Yep c'est ça. Cool si t'es OK. J'ai commencé à découper le fichier source en fichiers qui regroupent par thématique.J'ai créé les fonctions pour la dispersion. 

Pour la mutation c'est pas au point, il faut préciser coaltab. Deux solutions : soit on choisit d'ignorer le premier argument, soit on se creuse un peu la tête pour trouver un moyen similaire à Niche et Dispersion. Parce que ça me contrarie un peu quand même d'appliquer pour tout le monde la même méthode de référencement dans la liste coaltab et de pas faire une fonction dédiée... :)

Pour puller c'est un peu la foire : 
`git pull {repo} {remotebranchname}:{localbranchname}`
Ce qui devrait donner : 
`git pull origin nicheFunctions:nicheFunctions`
Mais j'ai jamais essayé, donc ce sera la surprise !!!

PS : Tu peux tout à fait checker les fichiers direct sur Github, en changeant de branche, en faisant gaffe de pas puller ou merger ! :)

**Comment by Becheler** [comment]
I created a new file, called "Prior distribution". It has to be filled, cause right now, there is only one distribution (the uniform one). The syntax seems redundant, but we need to give a name to prior distribution in order to call them when asking user for the list.

**Comment by Becheler** [comment]
We need to add error handling when filling the list, specifying the existing functions, re-asking for answer etc...

**Comment by Becheler** [comment]
I think we need to add a list for the growth rate in the Paramlist when asking for niche functions. Right now I defined r as strictely equal to K (just to have a toy). But it has to be changed :=)
